#!/bin/bash

BASHRC="$HOME/.bashrc"
INSTALLED_STR="installed_skopos"
BASH_SCRIPTS=$HOME/.bash

rc_rm_skopos()
{
  # https://unix.stackexchange.com/questions/26284/how-can-i-use-sed-to-replace-a-multi-line-string
  #sed -r -e '1,$H;$!d;g'  \
  sed -i~ -r -e '1,$H;$!d;g'  \
      -e 's/\n## '"$INSTALLED_STR"'\n(.*\n)+## end '"$INSTALLED_STR"'//' "$BASHRC"
}

rc_install_skopos()
{
  cat <<E >>"$BASHRC"

## $INSTALLED_STR
BASH_SCRIPTS="\$HOME"/.bash
export BASH_SCRIPTS

if [[ -e "\$BASH_SCRIPTS"/skopos/skopos.sh ]]; then
  source "\$BASH_SCRIPTS"/skopos/skopos.sh
  
  if [[ \$(echo "\$PATH" | grep -c "\$HOME"/bin) == 0 ]]
  then
    PATH="\${PATH:+\$PATH:}\$HOME/bin"
    export PATH
  fi
fi
## end $INSTALLED_STR
E
}

if mkdir -p "$BASH_SCRIPTS" 2>/dev/null; then
  if ! cp -avp .bash/* "$BASH_SCRIPTS"; then
    echo >&2 "Unable to copy files to $BASH_SCRIPTS"
    exit 8
  fi
fi

# this mkdir will not clobber
if mkdir -p "$HOME/bin" 2>/dev/null; then
  # This cp will not clobber any
  # existing files without explicit
  # permission.
  if cp -iavp bin/* "$HOME/bin"; then
    echo "Files installed successfully..."
  else
    echo >&2 "Installation didn't fully succeed, but things might still be OK."
    exit 2
  fi
else
  echo >&2 "Unable to mkdir $HOME/bin. RC was $?"
  exit 4
fi

if [[ $(grep -c "$INSTALLED_STR" "$BASHRC") == 0 ]]; then
  rc_install_skopos
else
  rc_rm_skopos
  rc_install_skopos
fi

echo "Installation is complete. You should logout and log back in, or source your $BASHRC"
